# 程序的端口号，context-path
server:
  port: 8080
  context-path: /boot

# 属性配置,在java文件中，可以用value("${}") 来为变量注入属性
girl:
  name: zhenhong
  age: 24
  content: content:name${name},age${age}

# 另外可以通过配置文件制定不同环境的配置文
# https://blog.csdn.net/bigtree_3721/article/details/78068121
# spring:
  # profiles:
    # active: test

# 数据库配置
spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
# ddl_auto: create 代表在数据库创建表，update 代表更新，首次启动需要create ,
# 如果你想通过hibernate 注解的方式创建数据库的表的话，之后需要改为 update.